spring:
  application:
    name: {{PROJECT_NAME}}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/{{PROJECT_NAME}}}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  threads:
    virtual:
      enabled: true

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

api:
  info:
    title: ${spring.application.name}
    version: ${project.version:0.0.1}
